import re
from typing import List, Dict, Tuple, Optional
from backend.models.evidence import EvidenceItem
from backend.utils.text import normalize_text, calculate_jaccard_similarity

GENERIC_CANONICAL_MAP = {   'entity-aiims': {   'aliases': [   'aiims',
                                       'aiims delhi',
                                       'all india institute of medical sciences',
                                       'aiims new delhi'],
                        'canonical_name': 'All India Institute of Medical Sciences (AIIMS New Delhi)'},
    'entity-al-jawahar': {   'aliases': [   'al jawahar',
                                            'al jawahar jama masjid',
                                            'al jawahar restaurant',
                                            'al jawahar delhi'],
                             'canonical_name': 'Al Jawahar Restaurant'},
    'entity-andc': {   'aliases': [   'andc',
                                      'acharya narendra dev college',
                                      'acharya narendra dev',
                                      'andc du',
                                      'andc kalkaji'],
                       'canonical_name': 'Acharya Narendra Dev College (ANDC)'},
    'entity-andhra-bhavan': {   'aliases': [   'andhra bhavan',
                                               'andhra bhavan canteen',
                                               'andhra bhawan',
                                               'andhra canteen delhi'],
                                'canonical_name': 'Andhra Bhavan Canteen'},
    'entity-arsd': {   'aliases': [   'arsd',
                                      'atma ram sanatan dharma college',
                                      'arsd college',
                                      'arsd du',
                                      'arsd south campus'],
                       'canonical_name': 'Atma Ram Sanatan Dharma College (ARSD)'},
    'entity-artusi-gk2': {   'aliases': ['artusi', 'artusi ristorante', 'artusi gk2', 'artusi greater kailash'],
                             'canonical_name': 'Artusi Ristorante e Bar'},
    'entity-aslam-chicken': {   'aliases': [   'aslam chicken',
                                               'aslam butter chicken',
                                               'aslam chicken jama masjid',
                                               'aslam old delhi'],
                                'canonical_name': 'Aslam Chicken (Jama Masjid)'},
    'entity-bhagini-nivedita': {   'aliases': [   'bhagini nivedita college',
                                                  'bnc',
                                                  'bnc du',
                                                  'bhagini nivedita najafgarh'],
                                   'canonical_name': 'Bhagini Nivedita College (BNC)'},
    'entity-bharati': {   'aliases': [   'bharati college',
                                         'bharati du',
                                         'bharati college janakpuri',
                                         'bharati college delhi'],
                          'canonical_name': 'Bharati College'},
    'entity-big-chill-khan': {   'aliases': [   'the big chill cafe',
                                                'big chill',
                                                'big chill khan market',
                                                'big chill delhi'],
                                 'canonical_name': 'The Big Chill Café (Khan Market)'},
    'entity-billu-hut-nsp': {   'aliases': [   'billu hut',
                                               "billu's hut",
                                               'billu hut nsp',
                                               'billu hut pitampura',
                                               'billus hut'],
                                'canonical_name': "Billu's Hut"},
    'entity-bukhara': {   'aliases': [   'bukhara',
                                         'bukhara itc maurya',
                                         'bukhara delhi',
                                         'dal bukhara',
                                         'bukhara chanakyapuri'],
                          'canonical_name': 'Bukhara'},
    'entity-burma-burma-saket': {   'aliases': [   'burma burma',
                                                   'burma burma saket',
                                                   'burma burma delhi',
                                                   'burma burma select citywalk'],
                                    'canonical_name': 'Burma Burma Restaurant & Tea Room'},
    'entity-caffe-tonino-cp': {   'aliases': [   'caffè tonino',
                                                 'caffe tonino',
                                                 'tonino cp',
                                                 'caffe tonino connaught place',
                                                 'tonino plaza cinema'],
                                  'canonical_name': 'Caffè Tonino'},
    'entity-carnatic-cafe-lodhi': {   'aliases': [   'carnatic cafe',
                                                     'carnatic cafe lodhi',
                                                     'carnatic cafe delhi',
                                                     'carnatic dosa'],
                                      'canonical_name': 'Carnatic Cafe (Lodhi Colony)'},
    'entity-chili-dwarka': {   'aliases': [   'pavilion 75',
                                              'welcomhotel dwarka dining',
                                              'itc welcomhotel dwarka',
                                              'pavilion 75 buffet'],
                               'canonical_name': 'Pavilion 75 (Welcomhotel Dwarka)'},
    'entity-coast-cafe-hkv': {   'aliases': [   'coast cafe',
                                                'coast cafe hkv',
                                                'coast cafe hauz khas',
                                                'coast cafe delhi'],
                                 'canonical_name': 'Coast Café (Hauz Khas Village)'},
    'entity-colonel-kababz': {   'aliases': ['colonel kababz', "colonel's kababz", 'colonels kababs defence colony'],
                                 'canonical_name': "Colonel's Kababz"},
    'entity-cvs': {   'aliases': ['cvs', 'college of vocational studies', 'cvs du', 'cvs south delhi'],
                      'canonical_name': 'College of Vocational Studies (CVS)'},
    'entity-dakshin': {   'aliases': [   'dakshin',
                                         'dakshin sheraton',
                                         'dakshin delhi',
                                         'sheraton saket dakshin',
                                         'dakshin itc'],
                          'canonical_name': 'Dakshin'},
    'entity-daryaganj-cp': {   'aliases': [   'daryaganj',
                                              'daryaganj restaurant',
                                              'daryaganj cp',
                                              'daryaganj connaught place',
                                              'the original 1947 butter chicken'],
                               'canonical_name': 'Daryaganj Restaurant'},
    'entity-dcac': {   'aliases': [   'dcac',
                                      'delhi college of arts and commerce',
                                      'dcac du',
                                      'dcac south campus',
                                      'dcac netaji nagar'],
                       'canonical_name': 'Delhi College of Arts and Commerce (DCAC)'},
    'entity-dduc': {   'aliases': [   'dduc',
                                      'deen dayal upadhyaya college',
                                      'deen dayal upadhyay',
                                      'ddu college',
                                      'dduc dwarka'],
                       'canonical_name': 'Deen Dayal Upadhyaya College (DDUC)'},
    'entity-defence-bakery': {   'aliases': ['defence bakery', 'defence colony bakery', 'defence bakery delhi'],
                                 'canonical_name': 'Defence Bakery'},
    'entity-delhi-o-delhi': {   'aliases': [   'delhi o delhi',
                                               "delhi 'o' delhi",
                                               'ihc dining',
                                               'india habitat centre dining',
                                               'delhi o delhi ihc'],
                                'canonical_name': "Delhi 'O' Delhi"},
    'entity-diggin-anand-lok': {   'aliases': ['diggin', 'diggin cafe', 'diggin anand lok', 'diggin opposite gargi'],
                                   'canonical_name': 'Diggin (Anand Lok)'},
    'entity-dolma-aunty-momos': {   'aliases': [   'dolma aunty momos',
                                                   'dolma aunty',
                                                   'dolma momos lajpat nagar',
                                                   'dolma momos delhi'],
                                    'canonical_name': 'Dolma Aunty Momos'},
    'entity-drc': {   'aliases': ['drc', 'daulat ram college', 'daulat ram', 'drc du', 'drc north campus'],
                      'canonical_name': 'Daulat Ram College (DRC)'},
    'entity-drool-kitchen-dwarka': {   'aliases': [   'drool kitchen',
                                                      'drool kitchen dwarka',
                                                      'drool kitchen sector 10',
                                                      'drool dwarka'],
                                       'canonical_name': 'Drool Kitchen'},
    'entity-dtu': {   'aliases': [   'dtu',
                                     'delhi technological university',
                                     'dce',
                                     'delhi college of engineering',
                                     'dtu delhi',
                                     'dtu bawana',
                                     'dtu rohini'],
                      'canonical_name': 'Delhi Technological University (DTU, formerly DCE)'},
    'entity-farzi-cafe-cp': {   'aliases': [   'farzi cafe',
                                               'farzi cafe cp',
                                               'farzi cafe connaught place',
                                               'farzi cafe delhi'],
                                'canonical_name': 'Farzi Café'},
    'entity-gargi': {   'aliases': ['gargi', 'gargi college', 'gargi du', 'gargi south campus', 'gargi college delhi'],
                        'canonical_name': 'Gargi College'},
    'entity-gargi-college': {   'aliases': [   'gargi college',
                                               'gargi',
                                               'gargi du',
                                               'gargi south campus',
                                               'gargi college delhi'],
                                'canonical_name': 'Gargi College'},
    'entity-ggsipu': {   'aliases': [   'ggsipu',
                                        'ipu',
                                        'guru gobind singh indraprastha university',
                                        'ip university',
                                        'ggsipu dwarka',
                                        'ipu dwarka'],
                         'canonical_name': 'Guru Gobind Singh Indraprastha University (GGSIPU Main Campus)'},
    'entity-hansraj-college': {   'aliases': [   'hansraj college',
                                                 'hansraj',
                                                 'hans raj',
                                                 'hansraj du',
                                                 'hansraj north campus'],
                                  'canonical_name': 'Hansraj College'},
    'entity-hindu-college': {   'aliases': [   'hindu college',
                                               'hindu',
                                               'hindu du',
                                               'hindu college delhi',
                                               'hindu north campus'],
                                'canonical_name': 'Hindu College'},
    'entity-igdtuw': {   'aliases': [   'igdtuw',
                                        'indira gandhi delhi technical university for women',
                                        'igdtu',
                                        'igdtuw kashmere gate'],
                         'canonical_name': 'Indira Gandhi Delhi Technical University for Women (IGDTUW)'},
    'entity-ihe': {   'aliases': ['ihe', 'institute of home economics', 'ihe du', 'ihe hauz khas'],
                      'canonical_name': 'Institute of Home Economics (IHE)'},
    'entity-iiitd': {   'aliases': [   'iiitd',
                                       'iiit delhi',
                                       'indraprastha institute of information technology',
                                       'iiit-d',
                                       'iiit okhla'],
                        'canonical_name': 'Indraprastha Institute of Information Technology Delhi (IIIT-Delhi)'},
    'entity-indian-accent': {   'aliases': [   'indian accent',
                                               'indian accent delhi',
                                               'the lodhi restaurant',
                                               'manish mehrotra restaurant',
                                               'indian accent lodhi'],
                                'canonical_name': 'Indian Accent'},
    'entity-institution-a': {   'aliases': ['institution a', 'tech campus a', 'campus a', 'college a'],
                                'canonical_name': 'Institution A (Technical Campus)'},
    'entity-institution-b': {   'aliases': ['institution b', 'eng institute b', 'campus b', 'college b'],
                                'canonical_name': 'Institution B (Engineering Institute)'},
    'entity-institution-c': {   'aliases': ['institution c', 'university campus c', 'campus c', 'state university c'],
                                'canonical_name': 'Institution C (State University Campus)'},
    'entity-institution-d': {   'aliases': ['institution d', 'tech institute d', 'campus d', 'college d'],
                                'canonical_name': 'Institution D (Institute of Technology)'},
    'entity-ipcw': {   'aliases': [   'ipcw',
                                      'indraprastha college for women',
                                      'ip college',
                                      'ip college du',
                                      'ip college civil lines'],
                       'canonical_name': 'Indraprastha College for Women (IP College)'},
    'entity-jmc': {   'aliases': ['jmc', 'jesus and mary college', 'jmc du', 'jmc chanakyapuri', 'jmc delhi'],
                      'canonical_name': 'Jesus and Mary College (JMC)'},
    'entity-jmi': {   'aliases': ['jmi', 'jamia millia islamia', 'jamia', 'jamia university', 'jamia engineering'],
                      'canonical_name': 'Jamia Millia Islamia (JMI)'},
    'entity-kake-da-hotel': {   'aliases': [   'kake da hotel',
                                               'kake da hotel cp',
                                               'kake da hotel connaught place',
                                               'kake da hotel delhi'],
                                'canonical_name': 'Kake Da Hotel'},
    'entity-karims': {   'aliases': [   "karim's",
                                        'karims',
                                        "karim's jama masjid",
                                        'karim hotel old delhi',
                                        'karims delhi',
                                        'karim old delhi'],
                         'canonical_name': "Karim's (Jama Masjid)"},
    'entity-keshav-mahavidyalaya': {   'aliases': [   'keshav mahavidyalaya',
                                                      'kmv du',
                                                      'keshav college',
                                                      'keshav',
                                                      'keshav mahavidyalaya pitampura'],
                                       'canonical_name': 'Keshav Mahavidyalaya'},
    'entity-keventers-cp': {   'aliases': [   'keventers',
                                              'keventers cp',
                                              'original keventers',
                                              'keventers connaught place'],
                               'canonical_name': 'Keventers (Original Milkshake Stand)'},
    'entity-khan-chacha': {   'aliases': [   'khan chacha',
                                             'khan chacha khan market',
                                             'khan chacha rolls',
                                             'khan chacha delhi'],
                              'canonical_name': 'Khan Chacha'},
    'entity-kuremal-kulfi': {   'aliases': [   'kuremal kulfi',
                                               'kuremal mohan lal',
                                               'kuremal kulfi chawri bazar',
                                               'stuffed kulfi delhi'],
                                'canonical_name': 'Kuremal Mohan Lal Kulfi Wale'},
    'entity-leos-pizzeria-vasant-vihar': {   'aliases': [   'leos pizzeria',
                                                            "leo's pizzeria",
                                                            'leos pizza vasant vihar',
                                                            'leos pizza delhi'],
                                             'canonical_name': "Leo's Pizzeria"},
    'entity-lhmc': {   'aliases': ['lhmc', 'lady hardinge medical college', 'lady hardinge', 'lhmc delhi'],
                       'canonical_name': 'Lady Hardinge Medical College (LHMC)'},
    'entity-maharaja-agrasen': {   'aliases': [   'maharaja agrasen college',
                                                  'mac du',
                                                  'mac delhi',
                                                  'agrasen college du',
                                                  'maharaja agrasen vasundhara'],
                                   'canonical_name': 'Maharaja Agrasen College'},
    'entity-mait': {   'aliases': [   'mait',
                                      'maharaja agrasen institute of technology',
                                      'mait rohini',
                                      'mait ipu',
                                      'mait btech'],
                       'canonical_name': 'Maharaja Agrasen Institute of Technology (MAIT)'},
    'entity-miranda-house': {   'aliases': [   'miranda house',
                                               'miranda',
                                               'mh',
                                               'mh du',
                                               'miranda house delhi',
                                               'miranda college'],
                                'canonical_name': 'Miranda House'},
    'entity-moti-mahal-delux-south-ex': {   'aliases': [   'moti mahal',
                                                           'moti mahal delux',
                                                           'moti mahal south ex',
                                                           'moti mahal butter chicken'],
                                            'canonical_name': 'Moti Mahal Delux (South Extension II)'},
    'entity-motilal-nehru': {   'aliases': [   'mlnc',
                                               'motilal nehru college',
                                               'motilal nehru du',
                                               'motilal nehru south campus'],
                                'canonical_name': 'Motilal Nehru College (MLNC)'},
    'entity-msi': {   'aliases': ['msi', 'maharaja surajmal institute', 'msi janakpuri', 'msi ipu'],
                      'canonical_name': 'Maharaja Surajmal Institute (MSI)'},
    'entity-msit': {   'aliases': ['msit', 'maharaja surajmal institute of technology', 'msit janakpuri', 'msit btech'],
                       'canonical_name': 'Maharaja Surajmal Institute of Technology (MSIT)'},
    'entity-music-mountain-gk1': {   'aliases': [   'music and mountains',
                                                    'music & mountains',
                                                    'hillside cafe gk1',
                                                    'music and mountains delhi'],
                                     'canonical_name': 'Music & Mountains - Hillside Cafe'},
    'entity-nagaland-kitchen-greenpark': {   'aliases': [   'nagaland kitchen',
                                                            'nagaland kitchen green park',
                                                            'naga food delhi',
                                                            'nagaland restaurant'],
                                             'canonical_name': 'Nagaland Kitchen'},
    'entity-nagpal-chole-bhature': {   'aliases': [   'nagpal chole bhature',
                                                      'nagpal amar colony',
                                                      'nagpal lajpat nagar',
                                                      'nagpal chhole'],
                                       'canonical_name': 'Nagpal Chole Bhature'},
    'entity-natraj-dahi-bhalla': {   'aliases': [   'natraj dahi bhalla',
                                                    'natraj chandni chowk',
                                                    'natraj aloo tikki',
                                                    'natraj dahi bhalla corner'],
                                     'canonical_name': 'Natraj Dahi Bhalla Corner'},
    'entity-nsut': {   'aliases': [   'nsut',
                                      'netaji subhas university of technology',
                                      'nsit',
                                      'netaji subhash',
                                      'nsut dwarka',
                                      'nsit dwarka'],
                       'canonical_name': 'Netaji Subhas University of Technology (NSUT, formerly NSIT)'},
    'entity-olive-mehrauli': {   'aliases': [   'olive bar and kitchen',
                                                'olive mehrauli',
                                                'olive qutub',
                                                'olive bar & kitchen',
                                                'olive qutub mehrauli'],
                                 'canonical_name': 'Olive Bar & Kitchen'},
    'entity-paranthe-wali-gali': {   'aliases': [   'paranthe wali gali',
                                                    'gaya prasad paranthe',
                                                    'pandit gaya prasad',
                                                    'chandni chowk paranthe'],
                                     'canonical_name': 'Pt. Gaya Prasad Shiv Charan (Paranthe Wali Gali)'},
    'entity-pirates-of-grill-rajouri': {   'aliases': [   'pirates of grill',
                                                          'pirates of grill rajouri',
                                                          'pirates of grill delhi',
                                                          'rajouri buffet'],
                                           'canonical_name': 'Pirates of Grill (Rajouri Garden)'},
    'entity-qds-restaurant-hudson': {   'aliases': [   'qds',
                                                       "qd's",
                                                       'qds hudson lane',
                                                       'qds restaurant',
                                                       'qds tandoori momos'],
                                        'canonical_name': "QD's Restaurant (Hudson Lane)"},
    'entity-rajdhani': {   'aliases': [   'rajdhani college',
                                          'rajdhani du',
                                          'rajdhani college delhi',
                                          'rajdhani raja garden'],
                           'canonical_name': 'Rajdhani College'},
    'entity-rajinder-da-dhaba': {   'aliases': [   'rajinder da dhaba',
                                                   'rajinder dhaba',
                                                   'rajinder da dhaba safdarjung',
                                                   'rdd delhi'],
                                    'canonical_name': 'Rajinder Da Dhaba'},
    'entity-ram-lal-anand': {   'aliases': [   'rla',
                                               'ram lal anand college',
                                               'ram lal anand',
                                               'rla du',
                                               'rla south campus'],
                                'canonical_name': 'Ram Lal Anand College (RLA)'},
    'entity-ramjas': {   'aliases': [   'ramjas',
                                        'ramjas college',
                                        'ramjas du',
                                        'ramjas north campus',
                                        'ramjas college delhi'],
                         'canonical_name': 'Ramjas College'},
    'entity-ramjas-college': {   'aliases': [   'ramjas college',
                                                'ramjas',
                                                'ramjas du',
                                                'ramjas north campus',
                                                'ramjas college delhi'],
                                 'canonical_name': 'Ramjas College'},
    'entity-restaurant-a': {   'aliases': ['restaurant a', 'kitchen a', 'cafe a'],
                               'canonical_name': 'Restaurant A (Traditional Kitchen)'},
    'entity-roshan-di-kulfi': {   'aliases': ['roshan di kulfi', 'roshan kulfi karol bagh', 'roshan di kulfi delhi'],
                                  'canonical_name': 'Roshan Di Kulfi'},
    'entity-runway1-rohini': {   'aliases': [   'runway 1',
                                                'runway 1 rohini',
                                                'airplane restaurant rohini',
                                                'runway1 metro walk'],
                                 'canonical_name': 'Runway 1'},
    'entity-sagar-ratna-defence-colony': {   'aliases': [   'sagar ratna',
                                                            'sagar ratna defence colony',
                                                            'sagar ratna south indian',
                                                            'sagar ratna delhi'],
                                             'canonical_name': 'Sagar Ratna (Defence Colony)'},
    'entity-saravana-bhavan-cp': {   'aliases': [   'saravana bhavan',
                                                    'saravana bhavan cp',
                                                    'hsb delhi',
                                                    'saravana bhavan connaught place',
                                                    'hotel saravana bhavan'],
                                     'canonical_name': 'Saravana Bhavan'},
    'entity-sbsc': {   'aliases': [   'sbsc',
                                      'shaheed bhagat singh college',
                                      'bhagat singh college',
                                      'sbsc du',
                                      'sbsc south campus',
                                      'sbsc sheikh sarai'],
                       'canonical_name': 'Shaheed Bhagat Singh College (SBSC)'},
    'entity-sggscc': {   'aliases': [   'sggscc',
                                        'sri guru gobind singh college of commerce',
                                        'guru gobind singh college of commerce',
                                        'ggs',
                                        'sggs',
                                        'sggscc pitampura'],
                         'canonical_name': 'Sri Guru Gobind Singh College of Commerce (SGGSCC)'},
    'entity-sgtb-khalsa': {   'aliases': [   'sgtb khalsa',
                                             'khalsa college du',
                                             'sgtb khalsa college',
                                             'khalsa north campus'],
                              'canonical_name': 'Sri Guru Tegh Bahadur Khalsa College (SGTB Khalsa)'},
    'entity-shivaji': {   'aliases': ['shivaji college', 'shivaji du', 'shivaji college delhi', 'shivaji raja garden'],
                          'canonical_name': 'Shivaji College'},
    'entity-shyam-lal': {   'aliases': ['shyam lal college', 'slc', 'slc du', 'shyam lal shahdara'],
                            'canonical_name': 'Shyam Lal College (SLC)'},
    'entity-social-hkv': {   'aliases': ['social hkv', 'hauz khas social', 'social hauz khas', 'social cafe delhi'],
                             'canonical_name': 'Hauz Khas Social'},
    'entity-sodabottleopenerwala-khan': {   'aliases': [   'sodabottleopenerwala',
                                                           'soda bottle opener wala',
                                                           'sodabottleopenerwala khan market',
                                                           'parsi cafe delhi'],
                                            'canonical_name': 'SodaBottleOpenerWala (Khan Market)'},
    'entity-spice-art': {   'aliases': [   'spice art',
                                           'spice art crowne plaza',
                                           'spice art rohini',
                                           'crowne plaza spice art'],
                            'canonical_name': 'Spice Art'},
    'entity-srcasw': {   'aliases': ['srcasw', 'rajguru college', 'shaheed rajguru', 'rajguru du', 'srcasw vasundhara'],
                         'canonical_name': 'Shaheed Rajguru College of Applied Sciences for Women (SRCASW)'},
    'entity-srcc': {   'aliases': [   'srcc',
                                      'shri ram college of commerce',
                                      'shri ram college',
                                      'srcc delhi',
                                      'srcc north campus',
                                      'shriram college of commerce'],
                       'canonical_name': 'Shri Ram College of Commerce (SRCC)'},
    'entity-sscbs': {   'aliases': [   'sscbs',
                                       'shaheed sukhdev college of business studies',
                                       'shaheed sukhdev',
                                       'sukhdev',
                                       'cbs',
                                       'cbs du'],
                        'canonical_name': 'Shaheed Sukhdev College of Business Studies (SSCBS)'},
    'entity-st-stephens': {   'aliases': [   "st stephen's college",
                                             'st stephens',
                                             'stephens',
                                             "st stephen's",
                                             'stephens du',
                                             'stephens college delhi'],
                              'canonical_name': "St. Stephen's College"},
    'entity-suruchi-karol-bagh': {   'aliases': [   'suruchi',
                                                    'suruchi restaurant',
                                                    'suruchi karol bagh',
                                                    'suruchi veg thali'],
                                     'canonical_name': 'Suruchi Restaurant'},
    'entity-tamra': {   'aliases': [   'tamra',
                                       'tamra shangri la',
                                       'tamra delhi',
                                       'shangri la tamra',
                                       'tamra connaught place'],
                        'canonical_name': 'Tamra'},
    'entity-tapas-punjabi-bagh': {   'aliases': [   'take off scarlet',
                                                    'tos punjabi bagh',
                                                    'tos delhi',
                                                    'take off scarlet club road'],
                                     'canonical_name': 'Take Off Scarlet (TOS)'},
    'entity-venkateswara': {   'aliases': [   'venky',
                                              'sri venkateswara college',
                                              'venkateswara college',
                                              'svc du',
                                              'venky south campus'],
                               'canonical_name': 'Sri Venkateswara College (Venky)'},
    'entity-vivekananda': {   'aliases': [   'vivekananda college',
                                             'vivekananda du',
                                             'vivekananda college vivek vihar',
                                             'vivekananda east delhi'],
                              'canonical_name': 'Vivekananda College'},
    'entity-vmmc': {   'aliases': [   'vmmc',
                                      'vardhman mahavir medical college',
                                      'safdarjung medical college',
                                      'vmmc safdarjung'],
                       'canonical_name': 'Vardhman Mahavir Medical College & Safdarjung Hospital (VMMC)'},
    'entity-wengers': {   'aliases': ['wengers', "wenger's", 'wengers cp', 'wengers bakery', 'wengers connaught place'],
                          'canonical_name': "Wenger's"},
    'entity-wengers-deli': {   'aliases': ['wengers deli', "wenger's deli", 'wengers deli cp', 'wengers cafe'],
                               'canonical_name': "Wenger's Deli"},
    'entity-wood-box-cafe': {   'aliases': [   'wood box cafe',
                                               'the wood box cafe',
                                               'wood box hudson lane',
                                               'wood box cafe delhi'],
                                'canonical_name': 'The Wood Box Cafe'},
    'entity-yellow-bowl-pitampura': {   'aliases': [   'shake eat dance',
                                                       'shake eat dance nsp',
                                                       'shake eat dance pitampura',
                                                       'sed nsp'],
                                        'canonical_name': 'Shake Eat Dance'},
    'entity-yum-yum-cha-saket': {   'aliases': [   'yum yum cha',
                                                   'yum yum cha saket',
                                                   'yum yum cha select citywalk',
                                                   'yum yum cha delhi'],
                                    'canonical_name': 'Yum Yum Cha (Saket)'},
    'entity-zakir-husain': {   'aliases': [   'zhdc',
                                              'zakir husain delhi college',
                                              'zakir husain college',
                                              'zakir husain du',
                                              'zakir hussain'],
                               'canonical_name': 'Zakir Husain Delhi College (ZHDC)'}}

class EntityResolutionService:
    """
    Disambiguates informal mentions, abbreviations, and aliases into canonical entities.
    Applies strict confidence thresholding (0.75) to prevent erroneous merges
    solely based on surface similarity.
    """

    def __init__(self, registry: Optional[Dict[str, Dict]] = None, similarity_threshold: float = 0.75):
        self.registry = registry or GENERIC_CANONICAL_MAP
        self.similarity_threshold = similarity_threshold

    def resolve_text_to_entity(self, text: str) -> Tuple[Optional[str], float]:
        normalized_target = normalize_text(text)
        if not normalized_target:
            return None, 0.0

        # Phase 1: Exact alias or token boundary match (Confidence: 1.0)
        for entity_id, meta in self.registry.items():
            for alias in meta["aliases"]:
                normalized_alias = normalize_text(alias)
                pattern = rf'\b{re.escape(normalized_alias)}\b'
                if re.search(pattern, normalized_target):
                    return entity_id, 1.0

        # Phase 2: Fuzzy similarity match across token n-grams
        best_id: Optional[str] = None
        best_score: float = 0.0

        for entity_id, meta in self.registry.items():
            for alias in meta["aliases"]:
                sim = calculate_jaccard_similarity(normalized_target, alias)
                if sim > best_score:
                    best_score = sim
                    best_id = entity_id

        if best_score >= self.similarity_threshold:
            return best_id, round(best_score, 2)

        return None, 0.0

    def resolve_text_to_entity_id(self, text: str) -> Optional[str]:
        entity_id, _ = self.resolve_text_to_entity(text)
        return entity_id

    def group_evidence_by_entity(self, evidence_items: List[EvidenceItem]) -> Dict[str, List[EvidenceItem]]:
        grouped: Dict[str, List[EvidenceItem]] = {}

        for item in evidence_items:
            combined_text = f"{item.source_title} {item.excerpt} {item.entity_hint or ''}"
            matched_id, _ = self.resolve_text_to_entity(combined_text)

            if not matched_id:
                for ent_id in self.registry.keys():
                    short_key = ent_id.replace("entity-", "")
                    if short_key in item.id.lower():
                        matched_id = ent_id
                        break

            target_key = matched_id or "unresolved"
            if target_key not in grouped:
                grouped[target_key] = []
            grouped[target_key].append(item)

        return grouped
