import React from 'react';
import { ArrowLeft, FileText, Scale, ExternalLink, AlertCircle } from 'lucide-react';
import { tactileAudio } from '../../utils/audio';
import { CONTACT_EMAIL_PLACEHOLDER } from '../home/ContactSuggestionSection';

interface TermsPageProps {
  onBack: () => void;
}

export const TermsPage: React.FC<TermsPageProps> = ({ onBack }) => {
  return (
    <div className="min-h-screen bg-[#FAF8F5] text-[#18181B] py-24 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto space-y-12">
        {/* Top Back Navigation */}
        <div>
          <button
            onClick={() => {
              tactileAudio.playClick();
              onBack();
            }}
            className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-white border border-zinc-200 text-xs font-mono-code text-zinc-600 hover:text-[#18181B] hover:border-zinc-300 transition-all shadow-2xs cursor-pointer"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            <span>Back to Workspace</span>
          </button>
        </div>

        {/* Header */}
        <div className="space-y-4 border-b border-zinc-200 pb-8">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-zinc-100 border border-zinc-200/80 text-zinc-700 text-xs font-mono-code font-bold">
            <Scale className="w-3.5 h-3.5 text-zinc-600" />
            <span className="tracking-wider uppercase">Terms of Use & Attribution</span>
          </div>

          <h1 className="text-4xl sm:text-5xl font-editorial font-normal tracking-tight text-[#18181B]">
            Terms & Conditions
          </h1>

          <p className="text-sm text-zinc-500 font-mono-code">
            Effective Date: September 2026 • ReviewLens Intelligence Engine
          </p>
        </div>

        {/* Informational Guidance Alert */}
        <div className="p-5 rounded-2xl bg-amber-50/60 border border-amber-200/80 flex items-start gap-3.5">
          <AlertCircle className="w-5 h-5 text-amber-700 shrink-0 mt-0.5" />
          <div className="space-y-1 text-xs text-amber-900 leading-relaxed font-light">
            <strong className="font-semibold block text-amber-950 font-mono-code uppercase tracking-wider text-[11px]">
              Evidence Research Notice
            </strong>
            ReviewLens cross-examines public signals to highlight corroboration and conflicting viewpoints. It does not replace independent due diligence, professional evaluation, or personal inspection.
          </div>
        </div>

        {/* Detailed Sections */}
        <div className="space-y-8 text-sm text-zinc-700 leading-relaxed font-light">
          <section className="space-y-3">
            <h2 className="text-xl font-editorial text-[#18181B] font-normal">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing or using the ReviewLens research platform, you agree to these Terms and Conditions. If you disagree with any part of these terms, your option is to discontinue use of the service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-editorial text-[#18181B] font-normal">
              2. Nature of Intelligence Reports
            </h2>
            <p>
              ReviewLens provides synthesized research dossiers generated by parsing and cross-examining public data sources. All outputs represent algorithmic summaries, aspect extractions, and topological links. ReviewLens explicitly does not guarantee that third-party commentary is factual, complete, or unbiased.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-editorial text-[#18181B] font-normal">
              3. Data Attribution & Source Compliance
            </h2>
            <p>
              ReviewLens respects the intellectual property and licensing terms of all source providers:
            </p>
            <ul className="list-disc list-inside space-y-1.5 pl-2 text-zinc-600">
              <li>
                <strong className="text-zinc-800 font-medium">OpenStreetMap:</strong> Map data and geographic nodes are provided by OpenStreetMap contributors under the Open Database License (ODbL).
              </li>
              <li>
                <strong className="text-zinc-800 font-medium">Wikimedia Foundation:</strong> Institutional background excerpts are sourced from Wikipedia under Creative Commons Attribution-ShareAlike (CC-BY-SA 4.0).
              </li>
              <li>
                <strong className="text-zinc-800 font-medium">Reddit:</strong> Public community discussion excerpts are accessed via official Reddit OAuth developer interfaces in compliance with Reddit API terms.
              </li>
              <li>
                <strong className="text-zinc-800 font-medium">Google Places:</strong> Verified place IDs, coordinates, and address records are queried via official Google Places Platform endpoints.
              </li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-editorial text-[#18181B] font-normal">
              4. Live vs. Demonstration Data Policy
            </h2>
            <p>
              ReviewLens transparently tags every research run. When live API keys or endpoints are configured and responding, results are tagged as <code className="px-1.5 py-0.5 rounded bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs font-mono-code">LIVE_RESEARCH</code>. Unconfigured sources return clear notices without fabricating simulated commentary.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-editorial text-[#18181B] font-normal">
              5. Disclaimer of Warranties
            </h2>
            <p>
              ReviewLens is provided on an "as is" and "as available" basis without warranties of any kind, whether express or implied. In no event shall ReviewLens or its contributors be liable for decisions made based on aggregated community opinions.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-editorial text-[#18181B] font-normal">
              6. Contact & Inquiries
            </h2>
            <p>
              For questions regarding these Terms, please contact:{' '}
              <code className="px-2 py-0.5 rounded-md bg-zinc-100 border border-zinc-200 font-mono-code text-zinc-800 text-xs">
                {CONTACT_EMAIL_PLACEHOLDER}
              </code>
            </p>
          </section>
        </div>

        {/* Bottom Action */}
        <div className="pt-8 border-t border-zinc-200">
          <button
            onClick={() => {
              tactileAudio.playClick();
              onBack();
            }}
            className="px-6 py-3 rounded-full bg-[#18181B] hover:bg-[#27272A] text-white text-xs font-medium tracking-wide transition-all shadow-xs cursor-pointer"
          >
            Return to ReviewLens Workspace
          </button>
        </div>
      </div>
    </div>
  );
};
